server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://myfate7002.com:7002/eureka,http://myfate7001.com:7001/eureka
  instance:
    instance-id: myEurekaclient-8002
    prefer-ip-address: true
spring:
  application:
    name: eurekaClient
info:
  app.name: fate
  build.artifactId: myEurekaClient02
  build.version: 0.0.1-SNAPSHOT
